Modulo RDS para projeto maria-quiteria
mentoriaiac/iac-modulo-aws-rds pull request #2
Opened 2022-07-08 00:45 UTC by chnacib

# Modulo RDS para projeto maria-quiteria

- [x] Garanta que seu **topic/feature/bugfix branch** tenha uma branch nomeada e não a sua branch main esteja no PR
- [x] Dê um titulo que expresse o objetivo do PR
- [x] Associe seu PR a uma Issue criada no repositósito. Caso seja uma correção de linguagem ou pequenas correções, não é necessário
- [x] Descreva o objetivo do PR
- [x] Inclua links relevantes para a sua modificação/sugestão/correção
- [x] Descreva um passo-a-passo para testar o seu PR

## Issue

 [Link da Issue](https://github.com/mentoriaiac/iac-modulo-aws-rds/issues/1)
## Objetivo
O objetivo é fazer o deploy de um banco de dados Postgres utilizando o serviço RDS da AWS. Além de criar Parameters Store para dados sensíveis que serão utilizados como variável de ambiente no módulo ECS maria-quiteria. 

![projectrds](https://user-images.githubusercontent.com/84737230/177894125-0c3ac688-ccf2-4b82-bcf1-e3a08c8458ae.png)

## Referências
[Especificar dados sigilosos usando o Systems Manager Parameter Store](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data-parameters.html)

## Como testar

```
cd how_to_use_this_module
terraform init
terraform plan
terraform apply -auto-approve
```

2022-07-10 13:22 UTC, EzzioWMoreira commented on network.tf
> +
```suggestion
 
 
```

2022-07-10 13:23 UTC, EzzioWMoreira commented on network.tf
> +
@chnacib tá faltando uma linha em branco no final do arquivo.

2022-07-10 13:24 UTC, EzzioWMoreira commented on variable.tf
> +
Aqui também falta uma linha em branco no final do arquivo.

2022-07-10 15:58 UTC, gomex requested changes
Está ficando perfeito! Faltam apenas alguns detalhes ;) Parabéns!

2022-07-10 15:58 UTC, gomex commented on README.md
> +| Name | Description | Type | Default | Required |
Seria legal traduzir a descrição de todos as variáveis, que tal?

2022-07-10 15:58 UTC, gomex commented on rds.tf
> +  name                   = var.db_name
```suggestion
  db_name                   = var.db_name
```

2022-07-10 15:58 UTC, gomex commented on how_to_use_this_module/terrafile.tf
> +  parameters = [{
Esse parâmetros são todos da aplicação. Eu entendi que aqui ficaria apenas como exemplo, mas seria melhor colocar outros exemplos, pra não confundir. Vou colocar um exemplo abaixo.

2022-07-10 15:58 UTC, gomex commented on how_to_use_this_module/terrafile.tf
> +    },
```suggestion
  parameters = [{
    name        = "parametro_adicional_do_rds",
    description = "Parâmetro adicional que precise ser adicionado na perspectiva do RDS",
    type        = "String",
    value       = " "
    },
```

2022-07-10 15:58 UTC, gomex commented on network.tf
> +    cidr_blocks = ["0.0.0.0/0"]
Assim que fizermos merge disso, seria legal criarmos uma issue pra melhorar o controle de acesso ao RDS, mas isso fica pra uma próxima oportunidade ;)

2022-07-10 15:58 UTC, gomex commented on output.tf
> +output "rds_hostname" {
Que tal traduzir os outputs também?

2022-07-10 15:58 UTC, gomex commented on rds.tf
> +  name                   = var.db_name
O input name está depreciado.

2022-07-10 15:58 UTC, gomex commented on variable.tf
> +    Environment : "Production",
Seria legal pedir esse environment no modulo, assim colocaríamos como tag a parte e até mesmo podemos usar o env para ser workspace, que tal?

2022-07-10 15:58 UTC, gomex commented on rds.tf
> +  publicly_accessible    = true
Isso precisa ser uma opção via variável do terraform.

2022-07-13 00:13 UTC, chnacib commented on network.tf
> +
Feito

2022-07-13 00:14 UTC, chnacib commented on variable.tf
> +
Feito

2022-07-13 00:14 UTC, chnacib commented on README.md
> +| Name | Description | Type | Default | Required |
Descrições de variáveis traduziadas

2022-07-13 00:15 UTC, chnacib commented on rds.tf
> +  name                   = var.db_name
Foi alterado o argumento "name" para "db_name"

2022-07-13 00:18 UTC, chnacib commented on how_to_use_this_module/terrafile.tf
> +    },
Foi feito alteração na descrição. Desta forma acredito que realmente ficou mais claro o objetivo do parâmetro.

2022-07-13 00:19 UTC, chnacib commented on network.tf
> +    cidr_blocks = ["0.0.0.0/0"]
Concordo. Acho que a ideia é colocar o security group do service do ECS como source no security group do RDS.

2022-07-13 00:19 UTC, chnacib commented on output.tf
> +output "rds_hostname" {
Tradução feita.

2022-07-13 00:20 UTC, chnacib commented on variable.tf
> +    Environment : "Production",
a variável default_tags agora está dentro do módulo, deixando a default apenas como exemplo.

2022-07-13 00:20 UTC, chnacib commented on rds.tf
> +  publicly_accessible    = true
Obrigado, realmente passou despercebido

2022-07-13 01:23 UTC, gomex requested changes
Parabéns! Muito bom!

2022-07-13 01:24 UTC, merged